version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: agr_nomin_db
    environment:
      POSTGRES_USER: agruser
      POSTGRES_PASSWORD: agrpassword
      POSTGRES_DB: agrnomin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
